# -*- coding: utf-8 -*-
"""lab04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jhVFvlGZSITAuaFCvcTI0XNkREz9JHce

Danny Ryan
2/22/20
Lab 4: Classification and KNN
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

file_link = 'https://drive.google.com/uc?export=download&id=1872WZovmmIRvyAra5AENBfUuVetA77ag'
df = pd.read_csv(file_link)
df

df.head(6)

X = df[['Textbook', 'Videos', 'Lecture', 'Discussion', 'Problems', 'Proactive', 'CodeExperience', 'MotivatedByFun','MotivatedByChallenge','MotivatedByGrades','MotivatedByJob' ]].values

X

y = df['Grade'].values
y

from sklearn.model_selection import train_test_split

Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.5, random_state=0)
print('Xtrain.shape:', Xtrain.shape)
print('ytrain.shape:', ytrain.shape)
print('Xtest.shape:', Xtest.shape)
print('ytest.shape:', ytest.shape)

from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=2, metric='euclidean')
model.fit(Xtrain, ytrain)

ypred = model.predict(Xtest)
ypred

ypred == ytest

from sklearn.metrics import accuracy_score
accuracy_score(ytest, ypred)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest, ypred)
print(cm)



import seaborn as sns;

sns.heatmap(cm, square=True, annot=True, fmt='d', cbar=True, cmap="PuBu",
                    xticklabels=model.classes_,
                    yticklabels=model.classes_)

plt.xlabel('Predicted Grade');
plt.ylabel('True Grade')
plt.title('Predicted vs. True Grade Confusion Matrix')
plt.show()

"""
Overall, the most accurete k-value I could find was k=2, which resulted in an 
accurecy of 53.57%. This is better than random chance, as I would assume a 
random chance model to be correct (1/5) or 20% of the time.



My model is best at predicting an A, as in that category my model had a sucess 
rate of 80%, which was the best of every grade. My model was worst at predicting a C, of which it is only accurete 46 percent of the time, 
which was the worst of every grade when compared.
"""

